version: "3.3"

services:
  api:
    build:
      context: .
    env_file:
      - ".env"
    ports:
      - 3001:3001
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
      - elastic
    volumes:
      - .:/usr/src/app
    command: bundle exec rails server --port 3001 --binding 0.0.0.0 -e development

  web:
    build: ./client
    ports:
      - 3000:3000
    depends_on:
      - api
    env_file:
      - ".env"

  db:
    image: postgres:9.6.16-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  elastic:
    image: blacktop/elasticsearch
    ports:
      - 9200:9200
      - 9250:9250
    environment:
      - discovery.type=single-node
    env_file:
      - ".env"
