
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  password: postgres

development:
  <<: *default
  database: histohumans_development

test:
  <<: *default
  database: histohumans_test

production:
  <<: *default
  database: histohumans_production
  username: histohumans
  password: <%= ENV['HISTOHUMANS_DATABASE_PASSWORD'] %>
