development: &default
  adapter: postgresql
  database: <%= ENV['HISTOHUMANS_DATABASE_NAME'] %>
  encoding: utf8
  min_messages: warning
  pool: <%= Integer(ENV.fetch("DB_POOL", 5)) %>
  reaping_frequency: <%= Integer(ENV.fetch("DB_REAPING_FREQUENCY", 10)) %>
  timeout: 5000
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

test:
  <<: *default
  database: histohumans_test

production: &deploy
  database: <%= ENV['HISTOHUMANS_DATABASE_NAME'] %>
  username: <%= ENV['HISTOHUMANS_DATABASE_USERNAME'] %>
  password: <%= ENV['HISTOHUMANS_DATABASE_PASSWORD'] %>
  encoding: utf8
  min_messages: warning
  pool: <%= [Integer(ENV.fetch("MAX_THREADS", 5)), Integer(ENV.fetch("DB_POOL", 5))].max %>
  timeout: 5000
  url:  <%= ENV.fetch("DATABASE_URL", "") %>
